// Get Tasks Data
export const GET_TASKS_DATA_REQUEST = 'TASKS/GET_TASKS_DATA_REQUEST';
export const GET_TASKS_DATA_SUCCESS = 'TASKS/GET_TASKS_DATA_SUCCESS';

// Update Task Properties
export const SET_TASK_STATE_REQUEST = 'TASKS/SET_TASK_STATE_REQUEST';
export const SET_TASK_STATE_SUCCESS = 'TASKS/SET_TASK_STATE_SUCCESS';
